### ISSUE TITLE
Please change the license to GPLv3+

### ISSUE THREAD

**Issue by jagerman** [VityaSchel/bunsogs#1]
As per the terms of the [PySOGS](https://github.com/oxen-io/session-pysogs) [GPLv3+ license](https://github.com/oxen-io/session-pysogs/blob/dev/LICENSE.txt), derivative works must be licensed under the same (or a compatible license), and must preserve the Oxen Project copyright notice.

While I realize that this is an impressive undertaking and does not share the Python code implementation, it is still clearly a derivative work as it contains comment blocks directly from PySOGS, the PySOGS sqlite database schema, and the PySOGS source code implementation was clearly used in the development of this implementation (see some [discussion about the licensing of language ports](https://softwareengineering.stackexchange.com/questions/208776/would-copyrights-drop-if-i-re-write-open-source-project-into-another-language)) and must thus still comply with PySOGS's license terms.

**Comment by VityaSchel** [comment]
> As per the terms of the [PySOGS](https://github.com/oxen-io/session-pysogs) [GPLv3+ license](https://github.com/oxen-io/session-pysogs/blob/dev/LICENSE.txt), derivative works must be licensed under the same (or a compatible license), and must preserve the Oxen Project copyright notice.
> 
> While I realize that this is an impressive undertaking and does not share the Python code implementation, it is still clearly a derivative work as it contains comment blocks directly from PySOGS, the PySOGS sqlite database schema, and the PySOGS source code implementation was clearly used in the development of this implementation (see some [discussion about the licensing of language ports](https://softwareengineering.stackexchange.com/questions/208776/would-copyrights-drop-if-i-re-write-open-source-project-into-another-language)) and must thus still comply with PySOGS's license terms.

Hello there! Thank you for your contributions to Session and especially for clarifying nearby pysogs code comments blocks and sqlite schema. I believe opensource should remain free and permissive for everybody, so I will now create a fork of bunsogs with all code derived from pysogs removed and custom sqlite schema, while this version, compatible with pysogs, will have GPLv3 version as required by pysogs license terms. I will also publish migration tool that helps operators migrate from pysogs completely and once and for all, which will be licensed under gplv3 license, since it has sqlite schema. Hopefully, this will help grow community of SOGS operators and bring two useful new projects to Session universe. I was also going to publish Session Native client, which will now be slightly delayed, but this is a great reminder that I should always draw attention to licenses in code, especially if it's related to such free, permissive and transparent projects as Session messenger.

**Comment by VityaSchel** [comment]
Please let me know if I added the right license 🙏
I have never used it and will never do (aside from Session projects and projects which use this license and I derived code from), so I'm not sure if the full 674 lines license text is correct and works for bunsogs derived code from pysogs
If everything looks good, I'm closing this issue. Otherwise, please comment/reopen, and possibly submit pull request 🙂
Thank you for your attention to such close details of bunsogs!
